### ISSUE TITLE
Python throwing an error requiring a bytes-like object even though that seems to be what's being passed

### ISSUE THREAD

**Issue by dospunk** [amadeus/python-impact#9]
```
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 52514)
Traceback (most recent call last):
  File "C:\Users\MyName\AppData\Local\Programs\Python\Python36\lib\socketserver.py", line 317, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Users\MyName\AppData\Local\Programs\Python\Python36\lib\socketserver.py", line 348, in process_request
    self.finish_request(request, client_address)
  File "C:\Users\MyName\AppData\Local\Programs\Python\Python36\lib\socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\MyName\AppData\Local\Programs\Python\Python36\lib\socketserver.py", line 696, in __init__
    self.handle()
  File "C:\Users\MyName\AppData\Local\Programs\Python\Python36\lib\http\server.py", line 418, in handle
    self.handle_one_request()
  File "C:\Users\MyName\AppData\Local\Programs\Python\Python36\lib\http\server.py", line 406, in handle_one_request
    method()
  File ".\server.py", line 80, in do_GET
    self.route_request('GET')
  File ".\server.py", line 105, in route_request
    self.glob()
  File ".\server.py", line 180, in glob
    return self.send_json(files)
  File ".\server.py", line 47, in send_json
    self.send_response(json.dumps(obj), code, headers)
  File ".\server.py", line 61, in send_response
    self.wfile.write(mesg)
  File "C:\Users\MyName\AppData\Local\Programs\Python\Python36\lib\socketserver.py", line 775, in write
    self._sock.sendall(b)
TypeError: a bytes-like object is required, not 'str'
----------------------------------------
```
Here's my error message. I'm running Python 3.6.0 on Windows 10

**Comment by amadeus** [comment]
I haven't touched this project in years 😬, but pretty sure python 3 was never supported :x

**Comment by dospunk** [comment]
Oh I renamed py3_server to just server for ease of use for myself
